name: CICD - Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Cucumber Tests
        run: mvn clean test

      - name: Print Maven Test Logs on Failure
        if: failure()
        run: cat target/surefire-reports/*.txt || true

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/CucumberReports/Cucumber-reports.html

      - name: Upload Full Test Output (target/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-test-output
          path: target/
