name: CI - Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean install

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: target/CucumberReports/Cucumber-reports.html
